TERRAFORM_STATE_BUCKET={{terraform_state_bucket}}
TERRAFORM_STATE_BUCKET_LOCATION={{terraform_state_bucket_location}}
GOOGLE_PROJECT={{google_project}}
GOOGLE_REGION={{primary_region}}
SLACKBOT_NAME={{slackbot_name}}

GOOGLE_PROJECT_SERVICES= \
    cloud.googleapis.com \
    compute.googleapis.com \
    sourcerepo.googleapis.com \
    cloudbuild.googleapis.com \
    artifactregistry.googleapis.com \
    secretmanager.googleapis.com

include Makefile.mk
