TERRAFORM_STATE_BUCKET={{terraform_state_bucket}}
TERRAFORM_STATE_BUCKET_LOCATION={{terraform_state_bucket_location}}
GOOGLE_PROJECT={{google_project}}
GOOGLE_REGION={{primary_region}}

include Makefile.mk
